
PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS participants(id TEXT PRIMARY KEY,identity TEXT UNIQUE NOT NULL,name TEXT NOT NULL,relation TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS responses(id TEXT PRIMARY KEY,request_id TEXT UNIQUE NOT NULL,participant_id TEXT UNIQUE NOT NULL REFERENCES participants(id),gender TEXT NOT NULL,first_guess TEXT NOT NULL,short_note TEXT NOT NULL DEFAULT '',photo_key TEXT NOT NULL DEFAULT '',media_key TEXT NOT NULL DEFAULT '',submitted_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY,role TEXT NOT NULL,expires_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS throttle(key TEXT PRIMARY KEY,window INTEGER NOT NULL,count INTEGER NOT NULL,expires_at INTEGER NOT NULL);
INSERT OR IGNORE INTO settings(key,value) VALUES ('FORM_ACIK','TRUE'),('KATILIMCI_LISTESI_ZORUNLU','FALSE'),('CANLI_ACIKLAMA_MODU','FALSE'),('ETKINLIK_TARIHI','');
